### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by mai-space** [JabRef/themes.jabref.org#1]
Hello @Siedlerchr 

A few months ago I had developed the dracula theme for JabRef - if possible by any chance, I'd like to contribute it here.

[Link to my repository](https://github.com/mai-space/theme-jabref-dracula)

Best regards!

Joël

**Comment by Siedlerchr** [comment]
Yes, that would be great. I have created a subfolder structure for light and dark themes and created a folder for your where you can put yours https://github.com/JabRef/themes.jabref.org/tree/main/themes/DarkTheme/Dracula

**Comment by mai-space** [comment]
Nice!

I am gonna do that soon ^^
