### ISSUE TITLE
theme license

### ISSUE THREAD

**Issue by ghost** [JabRef/themes.jabref.org#11]
Hi

I want my themes to be fully free, so that anybody can change them and distribute.
I'm not a developer and don't know anything about licenses.
Can you write on the theme page the correct license for this?
I think there is nothing needed in the CSS file for this or can I put on the first line in comments the used license?
I saw in Base.css how comments are made.

**Comment by koppor** [comment]
To be consistent with JabRef, I vote for the MIT license. With the same content as https://github.com/JabRef/jabref/blob/main/LICENSE.md. (Year updated).

Reasons:

- MIT guarantees full freeness
- MIT prevents you from being hold liable for anything

More details at https://choosealicense.com/licenses/mit/

**Comment by ghost** [comment]
What to add and where in the CSS file? Or is it enough if I put the license file next to the CSS files?
Please check the PR if it's correct now.

https://github.com/JabRef/themes.jabref.org/pull/13
