### ISSUE TITLE
links

### ISSUE THREAD

**Issue by ghost** [JabRef/themes.jabref.org#6]
Hi

Maybe you can put a link to the themes website here ?

https://docs.jabref.org/advanced/custom-themes

And maybe the forum can have a custom theme/exporter section for questions and for sharing the theme website?

Because I think otherwise people won't even find the theme website because it's not linked to (except in my forum post which will sink to the bottom because I don't like to talk in public so much)

**Comment by Siedlerchr** [comment]
Hi, I added a link to the docs page now!
https://docs.jabref.org/advanced/custom-themes

I don't have the rights to create a new section in the forum, but will discuss with the other devs

**Comment by ghost** [comment]
> I don't have the rights to create a new section in the forum, but will discuss with the other devs

OK!
I think this will definitely let people discover the themes.

**Comment by Siedlerchr** [comment]
Yes! We also announced the themes on our social media accounts and this is also part of our release blog post

**Comment by ghost** [comment]
Can be closed!
